---
- name: create login user for installation & configuration
  hosts: all

  roles:
  - { role: login-user, tags: ['login-user'] }

- name: secure SSH
  hosts: all
  become: true

  roles:
  - { role: secure-ssh, tags: ['secure-ssh'] }

# NOTE: assumes the existence of:
# - an environment group that owns all of the variables we will need for our tests
# - a "default" group containing a (preferably single) host that is a member of the environment group
# - an "environ" variable set to the name of the environment group
- name: get environment vars for tests
  hosts: default
  connection: local
  tags:
    - testup

  tasks:
  - name: add localhost to the environment group to get the vars
    add_host:
      name: localhost
      group: "{{ environ }}"
    changed_when: false

- name: set up tests
  hosts: localhost
  connection: local

  roles:
  - { role: testup, tags: ['testup'], when: set_up_tests }
